# -*- coding: utf-8 -*-
"""4주차

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eji_x9THVE3AUeu24H06s2u3Qf19A5d7
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

plt.rc('font', family = 'NanumBarunGothic')

import matplotlib.pyplot as plt
import pandas as pd

df_temp = pd.read_csv('/content/seoul_temp.csv')
#df_temp.tail(5)
#df_temp.head(5)
#df_temp.describe()
df_temp.set_index('연도', inplace = True)
df_temp

plt.plot(df_temp.index , df_temp['평균기온'])
plt.title('avg temp')
plt.show()
plt.plot(df_temp.index , df_temp['최고기온'])
plt.title('max temp')
plt.show()

plt.figure(figsize = (15,10))
plt.plot(df_temp.index , df_temp['평균기온'], color = 'green',marker = '*')
plt.plot(df_temp.index , df_temp['최고기온'], color = 'red', marker = 'o')
plt.plot(df_temp.index , df_temp['최저기온'], color = 'blue',marker = 'v')
plt.grid()
plt.title('서울연간기온')
plt.xlabel('연도')
plt.ylabel('기온')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

mlist = np.random.randint(0,5,10)

fig, ax =plt.subplots()
ax.plot(mlist)
plt.show()

ax.plot(np.random.randint(0,5,10))
ax.plot(np.random.randint(5,10,10))
fig

fig, ax = plt.subplots(ncols=3,nrows=2, figsize=(6,6))

label = ['초코','딸기','치즈','생크림']
size = [40.0,30.0,20.0,10.0]

ax[0,2].pie(size,labels=label,autopct='%.1f%%')
fig

ax[0,1].plot(np.arange(1,11,1))
fig
ax[1,2].plot(np.arange(10,0,-1))
fig

x1 = np.random.rand(50)
y1= np.random.rand(50)

ax[0,0].scatter(x1,y1)
fig

label = ['A','B','AB','O']
size = [34.8,32.9,14.7,17.6]

ax[1,0].pie(size,labels=label,autopct='%.1f%%')
plt.show()

ax[1,1].bar(df_temp.index,df_temp['평균기온'],color = 'r')
fig