# -*- coding: utf-8 -*-
"""9주차

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qG1KKOwHnDdiZs0b-hX7clDBVcBCAJpO
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
import pandas as pd

plt.rc('font', family = 'NanumBarunGothic')

plt.rcParams['axes.unicode_minus'] = False

df = pd.read_csv('/content/행정구역별인구현황.csv')
df

df['행정구역'] = df['행정구역'].str.split().str[0]
#str[:-12]
df

df.columns = ['행정구역','총인구수','세대수','세대당인구','남자인구수','여자인구수','남여비율']
df

df = df.drop(index=0)
#df = df[:1]
df

df.nlargest(5,'총인구수')
#df.sort_values('총인구수',ascending = False)

df.plot.bar(x='행정구역',y='총인구수',color='red',figsize=(8,3))
plt.title('행정구역별 총인구수')
plt.grid()
plt.xticks(rotation = 45)
plt.show()

df_t = df.sort_values('세대당인구',ascending = False)

plt.plot(df_t['행정구역'],df_t['세대당인구'],marker = 'o',color='green')
plt.xticks(rotation=45)
plt.title('가구당 인구수')
plt.grid()
plt.show()

path = '/content/연령별인구현황.csv'
df_age = pd.read_csv(path)
df_age

df_age['행정구역'] = df_age['행정구역'].str.split('(').str[0]
df_age

df_age.set_index(df_age['행정구역'],inplace= True)
df_age

df_age = df_age.drop(columns = ['행정구역','2023년09월_계_총인구수', '2023년09월_계_연령구간인구수'])
df_age

import numpy as np

df_age.columns = np.arange(0,101)
df_age

path = '/content/동별연령별인구현황.csv'
df_dong = pd.read_csv(path)
df_dong

df_dong['행정구역'] = df_dong['행정구역'].str.split('(').str[0]

#df_dong.index = df_dong['행정구역']

#df_dong = df_dong.drop(columns = ['행정구역','2023년09월_계_총인구수','2023년09월_계_연령구간인구수'])

df_dong.columns = np.arrange(0,101)
df_dong