# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Axc6AkL53_LpDOdUe9VHbaVu8LQ6asll

물건 구매가
"""

price = int(input("물건 구매가를 입력하세요:"))
if price >= 10000 and price < 50000:
  print("구매가", price)
  print("할인율: 5%")
  print("할인금액:", price*5/100)
  print("지불금액:", price - price*5/100 )
elif price >= 50000 and price < 100000:
    print("구매가", price)
    print("할인율: 7.5%")
    print("할인금액:", price*75/1000)
    print("지불금액:",price - price*75/1000)
else:
    print("구매가", price)
    print("할인율: 10%")
    print("할인금액:", price*10/100)
    print("지불금액:",price -  price*10/100 )

"""국립공원 입장료"""

age = int(input("나이:"))
if age >= 65 or age <= 7:
  print("무료입니다")
elif age >= 8 and age <= 18:
  print("1000원입니다.")
else:
  print("3000원입니다.")

"""구구단"""

num = [1,2,3,4,5,6,7,8,9]

for n in num:
  multiply = num[]*n
  print(n,'x', , '=', multiply)

"""아이돌 순서"""

li_idol = ['뉴진스', '에스파', '르세라핌', '블랙핑크', '아이브']
li_idol.append('BTS')
li_idol.insert(2,'마마무')
idx = li_idol.index("르세라핌")
li_idol[idx]="여자아이들"
li_idol.remove('BTS')
li_idol

"""숫자 더하기"""

sum = 0
num = int(input("숫자:"))
while num != 0:
  sum+=num
  num = int(input("숫자:"))
print("합계",sum)

"""팩토리얼"""

n = int(input("몇 팩토리얼"))
f = 1
for i in range(n,0,-1):
  f *= i
print(f"{n}! = {f}")

"""사용자 원하는 구구단 출력"""

n = int(input("구구단 몇단을 출력할까요? :"))
for i in range(9):
  print(n,"x",i+1,"=", n*(i+1))

"""숫자 예상"""

import random
r = random.randint(1,10)
num = int(input("예상숫자:"))
while num != r:
  if num < r:
    print("up")
  elif num > r:
    print("down")
  num = int(input("예상숫자:"))
if num == r:
  print("정답!!")

